### ISSUE TITLE
Runtime failure with Quarkus 3.0.1.Final and 3.0.0 branch of Renarde

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#116]
I've upgraded my pom.xml to use the latest `Quarkus 3.0.1.Final` and the `3.0.0` branch of `Renarde` both security and main modules.

After changing all my references from `javax` to `jakarta`, etc. everything builds and deploys.

But when I make my first attempt at authorization checking I get the following error:

Is the 3.0.0 branch production ready?

If I try to use the `1.0.5` version which works with Quarkus 2.16.x in the 3.0.1.Final pom, I get errors from Renarde because it is still using the old `Javax` references.

```
2023-04-26 16:23:54,073 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /apple-touch-icon-precomposed.png failed, error id: f2fef1dc-3f33-4560-b3db-72b3797dc82f-3: java.lang.NoSuchMethodError: io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism: method 'void <init>()' not found
support-site     | 	at io.quarkiverse.renarde.util.RenardeJWTAuthMechanism.<init>(RenardeJWTAuthMechanism.java:22)
support-site     | 	at io.quarkiverse.renarde.util.RenardeJWTAuthMechanism_ClientProxy.<init>(Unknown Source)
support-site     | 	at io.quarkiverse.renarde.util.RenardeJWTAuthMechanism_Bean.proxy(Unknown Source)
support-site     | 	at io.quarkiverse.renarde.util.RenardeJWTAuthMechanism_Bean.get(Unknown Source)
support-site     | 	at io.quarkiverse.renarde.util.RenardeJWTAuthMechanism_Bean.get(Unknown Source)
support-site     | 	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:323)
support-site     | 	at io.quarkus.arc.impl.InstanceImpl$InstanceIterator.next(InstanceImpl.java:361)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.<init>(HttpAuthenticator.java:41)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.doCreate(Unknown Source)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(Unknown Source)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(Unknown Source)
support-site     | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
support-site     | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
support-site     | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
support-site     | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
support-site     | 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
support-site     | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.get(Unknown Source)
support-site     | 	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.get(Unknown Source)```

**Comment by schltgn** [comment]
Same problem here! 
For class io.quarkiverse.renarde.util.RenardeJWTAuthMechanism, IntelliJ shows the following: "There is no default constructor available in 'io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism'"

**Comment by omidontop** [comment]
Same problem here. I've created a fresh amazon-lambda project like this:

```bash
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-archetype \
       -DarchetypeVersion=3.0.2.Final
```

And simply added Renarde like this:

```bash
quarkus ext add io.quarkiverse.renarde:quarkus-renarde
```

**Comment by FroMage** [comment]
Should be fixed in `main`

**Comment by omidontop** [comment]
> Should be fixed in `main`

Amazing!! Thank you! Is 3.0.1 going to be released anytime soon?

**Comment by FroMage** [comment]
Yes, as soon as I fix another bug. Hopefully tomorrow.
